-- AlterTable
ALTER TABLE "Listing" ADD COLUMN IF NOT EXISTS "checkInMethod" TEXT;
ALTER TABLE "Listing" ADD COLUMN IF NOT EXISTS "infoVerifiedAt" TIMESTAMP(3);
ALTER TABLE "Listing" ADD COLUMN IF NOT EXISTS "verifiedAt" TIMESTAMP(3);
ALTER TABLE "Listing" ADD COLUMN IF NOT EXISTS "licenseType" TEXT;
ALTER TABLE "Listing" ADD COLUMN IF NOT EXISTS "licenseNumber" TEXT;
